export const START_LIFES = 6;
export const IMAGE_LIFES_MAP = {
  12: { x: -1, y: 0},
  11: { x: 0, y: 0},
  10: { x: 1, y: 0},
  9: { x: 2, y: 0},
  8: { x: 0, y: 1},
  7: { x: 1, y: 1},
  6: { x: 2, y: 1},
  5: { x: 0, y: 2},
  4: { x: 1, y: 2},
  3: { x: 2, y: 2},
  2: { x: 0, y: 3},
  1: { x: 1, y: 3},
  0: { x: 2, y: 3},
};
export const START_LETTERS = {
  a: null,
  b: null,
  c: null,
  d: null,
  e: null,
  f: null,
  g: null,
  h: null,
  i: null,
  j: null,
  k: null,
  l: null,
  m: null,
  n: null,
  o: null,
  p: null,
  q: null,
  r: null,
  s: null,
  t: null,
  u: null,
  v: null,
  w: null,
  x: null,
  y: null,
  z: null,
};
